// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUe1_flzG7YMVXcTXX1UC3tLGevS6ezQ',
    appId: '1:216581511223:web:9ca1c6ccb46b44d5d447b2',
    messagingSenderId: '216581511223',
    projectId: 'al-na7yh-27cba',
    authDomain: 'al-na7yh-27cba.firebaseapp.com',
    storageBucket: 'al-na7yh-27cba.firebasestorage.app',
    measurementId: 'G-DFLEY9324R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATAgU0uZHRxjvQhidhL6y8FB-aRJH-Hvo',
    appId: '1:216581511223:android:164e8ddc2aac7dd3d447b2',
    messagingSenderId: '216581511223',
    projectId: 'al-na7yh-27cba',
    storageBucket: 'al-na7yh-27cba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUe1_flzG7YMVXcTXX1UC3tLGevS6ezQ',
    appId: '1:216581511223:web:2003d54599150cded447b2',
    messagingSenderId: '216581511223',
    projectId: 'al-na7yh-27cba',
    authDomain: 'al-na7yh-27cba.firebaseapp.com',
    storageBucket: 'al-na7yh-27cba.firebasestorage.app',
    measurementId: 'G-G316LJX1CQ',
  );

}